language: python
sudo: false
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.8.5"
  - DJANGO="django==1.7.10"
  - DJANGO="django==1.6.11"
  - DJANGO="django==1.5.12"
  - DJANGO="django==1.4.22"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django==1.4.22"
    - python: "3.4"
      env: DJANGO="django==1.4.22"
    - python: "3.5"
      env: DJANGO="django==1.4.22"

install:
  - pip install $DJANGO --use-mirrors
  - pip install redis==2.10.3 --use-mirrors
  - pip install mock==1.0.1
  - pip install msgpack-python>=0.4.6

script:
  - (cd tests && python runtests.py)
  - (cd tests && python runtests-sharded.py)
  - (cd tests && python runtests-herd.py)
  - (cd tests && python runtests-json.py)
  - (cd tests && python runtests-msgpack.py)

services:
  - redis-server

notifications:
  email:
    recipients:
      - niwi@niwi.be
    on_success: change
    on_failure: change
