language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.5.1
  - DJANGO_VERSION=1.4.3
install:
  - pip install django==$DJANGO_VERSION --use-mirrors
  - pip install redis --use-mirrors
script:
  - python runtests.py
  - python runtests-sharded.py
services:
  - redis-server
notifications:
  email:
    recipients:
      - niwi@niwi.be
    on_success: change
    on_failure: change
